# Tarea 2

### 1. Contraseña

In [8]:
contraseña = "fechadenacimiento"
inp = input("introduce la contraseña: ")

if len(inp) < len(contraseña):
    print("Te faltan caracteres")
elif len(inp) > len(contraseña):
    print("Son demasiados caracteres")
elif contraseña == inp:
    print("contraseña correcta")

introduce la contraseña:  fechadenacimiento


contraseña correcta


### 2. Karaoke

In [15]:
# aqui va el karaoke

### 3. numpy

In [56]:
import numpy as np

In [62]:
def punto(a, b):
    a = np.array(a)
    b = np.array(b)
    d = 0
    
    for i in range(len(a)):
        d += a[i]*b[i]
    
    print(d)

a = [1, 2, 3, 8, 5, 9, 5, 5, 3, 4, 7, 8, 9, 0]
b = [2, 14, 6, 7, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8]

punto(a, b)

335


#### 4. Producto matricial

In [57]:
import numpy as np

def prodmtr(A, B):
    A = np.array(A)
    B = np.array(B)

    n = A.shape[0] # n renglones
    m = A.shape[1] # m columnas
    k = B.shape[0] # k renglones
    mb = B.shape[1] # mb columnas
    

    X = np.zeros((n, k), int)

    for i in range(n):
        for j in range(k):
            for l in range(m):
                X[i, j] += A[i, l] * B[l, j]
   
    if m != mb:
        print("ERROR")
    else:
        print(X)

In [59]:
#Ejemplo que funciona
A = np.array([(1, 2, 3, 4, 1), (4, 5, 6, 8, 5), (2, 7, 9, 4, 5), (4, 2, 1, 0, 9), (7, 4, 0, 5, 1)])
B = np.array([(5, 3, 1, 9, 0), (0, 6, 2, 2, 5), (7, 3, 4, 5, 3), (1, 2, 1, 0, 6), (9, 0, 2, 8, 8)])
prodmtr(A, B)

[[ 39  32  23  36  51]
 [115  76  56 116 131]
 [122  83  66 117 126]
 [108  27  30 117  85]
 [ 49  55  22  79  58]]


In [61]:
#Ejemplo que no funciona
M = np.array([(1, 2, 3, 4), (4, 5, 6, 8), (2, 9, 4, 5), (4, 2, 1, 9), (4, 0, 5, 1)])
N = np.array([(3, 2, 1, 0, 9), (0, 6,7, 2, 5), (9, 1, 4, 8, 3), (7, 2, 1, 8, 6), (9, 0, 2, 8, 8)])
prodmtr(M, N)

ERROR


### 5. Matriz inversa

In [6]:
import numpy as np
def detinv(A):
    A = np.array(A)
    
    det =  A[0, 0]*(A[1, 1]*A[2, 2] - A[1, 2]*A[2, 1]) + A[0, 1]*(A[1, 2]*A[2, 0] - A[1, 0]*A[2, 2]) + A[0, 2]*(A[1, 0]*A[2, 1] - A[1, 1]*A[2, 0])
    #print(det)

    if det == 0:
        print("ERROR la matriz tiene determinante 0")
        
    else:
        inv = A*(1/det)
        print(inv)

In [8]:
#Ejemplo que funciona
B = np.array([(2, 2, 1), 
              (3, 5, 7), 
              (2, 4, 6)])
detinv(B)

[[-1.  -1.  -0.5]
 [-1.5 -2.5 -3.5]
 [-1.  -2.  -3. ]]


In [10]:
#Ejemplo que no funciona
X = np.array([(3, 2, 1), 
              (3, 5, 7), 
              (2, 4, 6)])
detinv(X)

ERROR la matriz tiene determinante 0


### 6. Sistema de ecuaciones de n incógnitas